# Berapa Banyak Waktu Dalam Menit Pemain Harus Menebak Kata
Time: 10
# Jumlah Hadiah terkecil dan Hadiah terbesar Pemain Dapat Menang Dari Menguraikan Kata Terlebih Dahulu
# EconomyAPI diperlukan jika hadiah diaktifkan
Activate Rewards: true
-Smallest Gift: 1000
-Biggest Prize: 5000
Say:
- Minecraft
- Dragon
- Sheep
