# Berapa Banyak Waktu Dalam Menit Pemain Harus Menebak Kata
Waktu: 10
# Jumlah Hadiah terkecil dan Hadiah terbesar Pemain Dapat Menang Dari Menguraikan Kata Terlebih Dahulu
# EconomyAPI diperlukan jika hadiah diaktifkan
Aktifkan Hadiah: true
Hadiah-Terkecil: 1000
Hadiah-Terbesar: 5000
Kata:
- Minecraft
- Dragon
- Sheep
